"""
Django settings for config project.

Generated by 'django-admin startproject' and maintained for the current SICAM backend.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/

NOTA IMPORTANTE SOBRE SEGURIDAD:
- Todos los valores sensibles están externalizados en variables de entorno.
- Ver .env.example para configuración esperada.
- NUNCA commitear .env a Git (está en .gitignore).
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializar django-environ
env = environ.Env()
# Leer archivo .env si existe (desarrollo local)
# En producción, las variables se pasan por sistema operativo
environ.Env.read_env(BASE_DIR / '.env')

# ============================================================================
# CONFIGURACIÓN CRÍTICA DE SEGURIDAD (EXTERNALIZADA)
# ============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# En producción, esta DEBE ser una clave larga, aleatoria y única.
# Generarla con: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
SECRET_KEY = env(
    'SECRET_KEY',
    default='django-insecure-validation-default-key-change-in-production'
)

# SECURITY WARNING: don't run with debug turned on in production!
# En producción, debe ser False
DEBUG = env.bool('DEBUG', default=True)

# En producción, especificar los dominios permitidos (separados por coma)
# Ejemplo: "api.sicam.com,www.sicam.com"
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '0.0.0.0'])

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'rest_framework',
    'corsheaders',

    # Apps propias
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ============================================================================
# CONFIGURACIÓN DE BASE DE DATOS
# ============================================================================
# 
# DESARROLLO LOCAL (default):
#   Usa SQLite (db.sqlite3) - sin variables de entorno necesarias
#
# PRODUCCIÓN con PostgreSQL:
#   Configurar las siguientes variables de entorno:
#   DB_ENGINE=django.db.backends.postgresql
#   DB_NAME=nombre_bd
#   DB_USER=usuario_db
#   DB_PASSWORD=contraseña_db
#   DB_HOST=host_db
#   DB_PORT=5432

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': env('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': env('DB_USER', default=''),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default=''),
        'PORT': env('DB_PORT', default=''),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = env('LANGUAGE_CODE', default='es-mx')

TIME_ZONE = env('TIME_ZONE', default='America/Mexico_City')

USE_I18N = True

USE_TZ = True

# ============================================================================
# CONFIGURACIÓN DE CORS
# ============================================================================
# En desarrollo: permite localhost:5173 (Vue dev server)
# En producción: especificar orígenes permitidos explícitamente
CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=[
        'http://localhost:5173',    # Vue dev server
        'http://localhost:3000',     # Alternative Vue port
        'http://127.0.0.1:5173',
        'http://127.0.0.1:3000',
    ]
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# ============================================================================
# CONFIGURACIÓN DE MICROSERVICIOS DE SEGMENTACIÓN
# ============================================================================
# URLs de los servicios de segmentación - debe estar disponible para orquestación
# 
# En desarrollo: usar localhost:8001 (saliva) y localhost:8002 (sangre) por defecto
# En producción: configurar URLs reales via variables de entorno
#
# Ejemplo:
#   SALIVA_SEGMENTATION_SERVICE_URL=http://saliva-service:8000
#   BLOOD_SEGMENTATION_SERVICE_URL=http://blood-service:8000

SEGMENTATION_SERVICES = {
    'SALIVA': {
        'url': env('SALIVA_SEGMENTATION_SERVICE_URL', default='http://localhost:8001'),
        'timeout': env.int('SALIVA_SERVICE_TIMEOUT', default=30),
    },
    'SANGRE': {
        'url': env('BLOOD_SEGMENTATION_SERVICE_URL', default='http://localhost:8002'),
        'timeout': env.int('BLOOD_SERVICE_TIMEOUT', default=30),
    },
}
