# Generated by Django 6.0 on 2026-01-22 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisPred',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(0, 'Abierto'), (1, 'En Proceso'), (2, 'Cerrado')], default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_caso_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='api.caso')),
                ('id_paciente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MuestraSaliva',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='muestras/saliva/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_saliva', to='api.analisispred')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='api.paciente'),
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('nucleos', models.IntegerField()),
                ('micronucleos', models.IntegerField()),
                ('membranas', models.IntegerField()),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.muestrasaliva')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisMascara',
            fields=[
                ('id_mascara_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mascara', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='mascaras/saliva/%Y/%m/')),
                ('algoritmo', models.CharField(max_length=100)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascaras', to='api.resultadoanalisis')),
            ],
        ),
    ]
