# Generated by Django 5.0.1 on 2026-07-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoSegmentacion',
            fields=[
                ('id_resultado_segmentacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_muestra', models.CharField(default='SALIVA', max_length=20)),
                ('respuesta_json', models.JSONField()),
                ('estado', models.CharField(default='COMPLETADO', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_segmentacion', to='api.muestrasaliva')),
            ],
        ),
    ]
