# Generated by Django 5.0.1 on 2026-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resultadosegmentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosegmentacion',
            name='resultado_normalizado',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
