# Generated by Django 5.0.1 on 2026-08-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resultadosegmentacion_resultado_normalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionSegmentacion',
            fields=[
                ('id_revision_segmentacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_revision', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADA', 'Validada')], default='BORRADOR', max_length=20)),
                ('resultado_editado', models.JSONField()),
                ('resumen', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('resultado_segmentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='api.resultadosegmentacion')),
            ],
            options={
                'ordering': ['numero_revision'],
            },
        ),
        migrations.AddConstraint(
            model_name='revisionsegmentacion',
            constraint=models.UniqueConstraint(fields=('resultado_segmentacion', 'numero_revision'), name='unique_revision_per_resultado_segmentacion'),
        ),
        migrations.AddConstraint(
            model_name='revisionsegmentacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'BORRADOR')), fields=('resultado_segmentacion',), name='unique_active_draft_per_resultado_segmentacion'),
        ),
    ]
