# Generated by Django 5.0.1 on 2026-08-21 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_revisionsegmentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosegmentacion',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_segmentacion', to='api.muestrasaliva'),
        ),
        migrations.CreateModel(
            name='MuestraSangre',
            fields=[
                ('id_muestra', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='muestras/sangre/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras_sangre', to='api.analisispred')),
            ],
        ),
        migrations.AddField(
            model_name='resultadosegmentacion',
            name='muestra_sangre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_segmentacion', to='api.muestrasangre'),
        ),
        migrations.AddConstraint(
            model_name='resultadosegmentacion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tipo_muestra', 'SALIVA'), ('muestra__isnull', False), ('muestra_sangre__isnull', True)), models.Q(('tipo_muestra', 'SANGRE'), ('muestra__isnull', True), ('muestra_sangre__isnull', False)), _connector='OR'), name='resultado_segmentacion_sample_type_consistency'),
        ),
    ]
