# Generated by Django 5.0.1 on 2026-08-28 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_resultadosegmentacion_muestra_muestrasangre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCaracterizacion',
            fields=[
                ('id_resultado_caracterizacion', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('AUTOMATICO', 'Automatico'), ('VALIDADA', 'Validada')], max_length=20)),
                ('sample_type', models.CharField(max_length=20)),
                ('algorithm_version', models.CharField(max_length=20)),
                ('resultado_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resultado_segmentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizaciones', to='api.resultadosegmentacion')),
                ('revision_segmentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caracterizaciones', to='api.revisionsegmentacion')),
            ],
            options={
                'ordering': ['-created_at', '-id_resultado_caracterizacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='resultadocaracterizacion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source_type', 'AUTOMATICO'), ('revision_segmentacion__isnull', True)), models.Q(('source_type', 'VALIDADA'), ('revision_segmentacion__isnull', False)), _connector='OR'), name='resultado_caracterizacion_source_consistency'),
        ),
    ]
