# Generated by Django 5.0.1 on 2026-09-23 23:44

from django.db import migrations, models


def backfill_saliva_strategy(apps, schema_editor):
    Resultado = apps.get_model('api', 'ResultadoSegmentacion')
    Resultado.objects.using(schema_editor.connection.alias).filter(
        muestra__isnull=False,
        muestra_sangre__isnull=True,
        segmentation_strategy__isnull=True,
    ).update(segmentation_strategy='CURRENT_CUSTOM_V1')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resultadocaracterizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosegmentacion',
            name='segmentation_strategy',
            field=models.CharField(blank=True, choices=[('CURRENT_CUSTOM_V1', 'Current custom v1'), ('ALT_CPSAM_MORPHOLOGICAL_V1', 'ALT cpsam morphological v1')], max_length=40, null=True),
        ),
        migrations.RunPython(backfill_saliva_strategy, migrations.RunPython.noop),
    ]
