# Generated by Django 5.0.1 on 2026-10-02 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_saliva_segmentation_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageJImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_key', models.CharField(max_length=100)),
                ('patient_namespace', models.CharField(max_length=64)),
                ('external_patient_id', models.CharField(max_length=100)),
                ('patient_key', models.CharField(max_length=100)),
                ('case_number', models.PositiveIntegerField()),
                ('logical_basename', models.CharField(max_length=255)),
                ('image_sha256', models.CharField(max_length=64)),
                ('mask_sha256', models.CharField(max_length=64)),
                ('sample_key', models.CharField(max_length=64, unique=True)),
                ('annotation_key', models.CharField(max_length=64, unique=True)),
                ('logical_key', models.CharField(max_length=64, unique=True)),
                ('converter_version', models.CharField(max_length=20)),
                ('contract_version', models.CharField(max_length=40)),
                ('source_mask_file', models.FileField(max_length=255, upload_to='imagej/source_masks/%Y/%m/')),
                ('status', models.CharField(choices=[('READY', 'Ready')], default='READY', max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='case_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='external_id_namespace',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paciente',
            name='external_patient_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='identity_mode',
            field=models.CharField(choices=[('IDENTIFIED', 'Identificado'), ('PSEUDONYMIZED', 'Pseudonimizado')], default='IDENTIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='initials',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resultadosegmentacion',
            name='base_origin',
            field=models.CharField(choices=[('AUTOMATIC', 'Automático'), ('MANUAL', 'Manual')], default='AUTOMATIC', max_length=12),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='caso',
            constraint=models.UniqueConstraint(condition=models.Q(('case_number__isnull', False)), fields=('paciente', 'case_number'), name='case_number_per_patient_unique'),
        ),
        migrations.AddConstraint(
            model_name='caso',
            constraint=models.CheckConstraint(check=models.Q(('case_number__isnull', True), ('case_number__gt', 0), _connector='OR'), name='case_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id_namespace', ''), _negated=True), fields=('external_id_namespace', 'external_patient_id'), name='patient_external_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('external_id_namespace', ''), ('external_patient_id', '')), models.Q(models.Q(('external_id_namespace', ''), _negated=True), models.Q(('external_patient_id', ''), _negated=True)), _connector='OR'), name='patient_external_identity_complete'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('identity_mode', 'IDENTIFIED'), models.Q(('nombre', ''), _negated=True), models.Q(('apellido', ''), _negated=True)), models.Q(('apellido', ''), ('identity_mode', 'PSEUDONYMIZED'), ('nombre', ''), models.Q(('initials', ''), _negated=True), models.Q(('external_id_namespace', ''), _negated=True), models.Q(('external_patient_id', ''), _negated=True)), _connector='OR'), name='patient_identity_mode_consistency'),
        ),
        migrations.AddConstraint(
            model_name='resultadosegmentacion',
            constraint=models.CheckConstraint(check=models.Q(('base_origin', 'AUTOMATIC'), models.Q(('base_origin', 'MANUAL'), ('segmentation_strategy__isnull', True), ('tipo_muestra', 'SALIVA')), _connector='OR'), name='segmentation_base_origin_consistent'),
        ),
        migrations.AddField(
            model_name='imagejimportrecord',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.caso'),
        ),
        migrations.AddField(
            model_name='imagejimportrecord',
            name='muestra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.muestrasaliva'),
        ),
        migrations.AddField(
            model_name='imagejimportrecord',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.paciente'),
        ),
        migrations.AddField(
            model_name='imagejimportrecord',
            name='resultado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.resultadosegmentacion'),
        ),
        migrations.AddConstraint(
            model_name='imagejimportrecord',
            constraint=models.CheckConstraint(check=models.Q(('case_number', 1), ('status', 'READY'), models.Q(('source_mask_file', ''), _negated=True)), name='imagej_record_ready'),
        ),
    ]
