# Generated by Django 5.0.1 on 2026-10-04 04:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_high_water_marks(apps, schema_editor):
    Result = apps.get_model('api', 'ResultadoSegmentacion')
    Revision = apps.get_model('api', 'RevisionSegmentacion')
    for result in Result.objects.using(schema_editor.connection.alias).iterator():
        high = 1
        snapshots = [result.resultado_normalizado, *Revision.objects.using(schema_editor.connection.alias).filter(
            resultado_segmentacion_id=result.pk).values_list('resultado_editado', flat=True)]
        for snapshot in snapshots:
            for obj in (snapshot or {}).get('objects', []):
                value = obj.get('id')
                if isinstance(value, int) and not isinstance(value, bool):
                    high = max(high, value + 1)
        Result.objects.using(schema_editor.connection.alias).filter(pk=result.pk).update(next_editorial_id=high)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_imagej_manual_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosegmentacion',
            name='next_editorial_id',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SegmentationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('CURRENT_CUSTOM_V1', 'Current custom v1'), ('ALT_CPSAM_MORPHOLOGICAL_V1', 'ALT cpsam morphological v1')], max_length=40)),
                ('target', models.CharField(choices=[('ALL', 'ALL'), ('MEMBRANES', 'MEMBRANES'), ('NUCLEI_AND_MICRONUCLEI', 'NUCLEI_AND_MICRONUCLEI')], max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=12)),
                ('request_metadata', models.JSONField(default=dict)),
                ('source_token', models.CharField(blank=True, max_length=64)),
                ('checkpoint', models.JSONField(null=True)),
                ('normalized_response', models.JSONField(null=True)),
                ('counts', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('resultado_segmentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='api.resultadosegmentacion')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='api.revisionsegmentacion')),
            ],
        ),
        migrations.RunPython(seed_high_water_marks, migrations.RunPython.noop),
    ]
